// Tier 2 (Atari) fixtures: base64 768-byte inputs plus the official .lmc
// oracle texts they must reproduce. Mirrors pal-fixtures.ts / lmc-fixtures.ts's
// embedding convention (base64-in-.ts sidesteps binary test-asset loading).
//
// MARIA_7800_PAL_B64 is generated by a throwaway script that parses the
// a7800p_colors table (and the NTSC_* macros it references) directly out of
// MAME's src/mame/atari/a7800.cpp at the pinned commit below, in the same
// order a7800p_colors lists them -- never hand-typed (mitigating
// hand-transcription risk on 768 values). TIA_2600_PAL_B64 is
// built by duplicating each of the 128 colors from the Wikipedia "List of
// video game console palettes" 2600 NTSC table (Lospec mirror
// atari-2600-ntsc-wikipedia) into adjacent pairs. One entry (hue 11, luma 0)
// uses 003c2c rather than the Lospec mirror's 00402c: the mirror carries a
// transcription typo at that cell (independently confirmed against
// MARIA_7800.lmc's electrically-related hue ramps and against every other
// source consulted), and using it would break byte-identity with the
// official TIA_2600.lmc for no reason other than propagating the error.
// TREBOR_COOL_PAL_B64 is a real-world 768-byte file: no official .lmc
// preset exists for any Trebor palette, so its golden entry asserts only
// parse+convert success, never byte-identity (see GOLDEN_PAIRS_TIER2's
// trailing breadth entry).

import { SystemId } from '../system';
import { FixtureSource } from './lmc-fixtures';

const RT4K_FIRMWARE_1510 =
  'https://cdn.jsdelivr.net/gh/retrotink-llc/firmware@main/RetroTINK-4K/Experimental/rt4k_1510.zip';
const firmwareLmc = (file: string): FixtureSource => ({
  url: RT4K_FIRMWARE_1510,
  pathInArchive: file,
});

// MAME commit d066f16134121f02a2fd9716582a17f8ee66f6d5, src/mame/atari/a7800.cpp.
export const MARIA_7800_PAL_SOURCE: FixtureSource = {
  url: 'https://raw.githubusercontent.com/mamedev/mame/d066f16134121f02a2fd9716582a17f8ee66f6d5/src/mame/atari/a7800.cpp',
  pathInArchive: 'src/mame/atari/a7800.cpp (a7800p_colors table)',
};
export const MARIA_7800_PAL_B64 =
  'AAAAERERIiIiMzMzREREVVVVZmZmd3d3iIiImZmZqqqqu7u7zMzM3d3d7u7u////ABcHDigIHzkIMEoIQVsIUmwIY30IdI4NhZ8elrAvp8FAuNJRyeNi2vRz6/+C/P+OGgcAKxgAPCkATToAXksAb1wAgG0AkX4Joo8as6ArxLE81cJN5tNe9+Rv//WD//eXMQAAQgYAUxcAZCgAdTkAhkoAl1sKqGwbuX0syo49259O7LBf/cFw/9KF/+Oc//SyPgAATwAAYAgAcRkAgioNkzsepEwvtV1Axm5R139i6JBz+aGD/7KY/8Ou/9TE/+XaPwADUAAPYQAbcg8rgyA8lDFNpUJetlNvx2SA2HWR6Yai+pez/6jI/7ne/8rv/9v0MwA1RABBVQBMZgxcdx1tiC5+mT+PqlCgu2GxzHLC3YPT7pTk/6Xk/7bp/8fu/9jzHQBcLgBoQAB0URCEYiGVczKmhEO3lVTIpmXZt3bqyIfr2Zjr6ans+7rr/8vv/9z0AgBxEwB9JAuMNRydRi2uVz6/aE/QeWDhinHym4L3rJP3vaT3zrX338b38Nf3/+j4AABoAAp8CBuQGSyhKj2yO07DTF/UXXDlboH2f5L/kKP/obT/ssX/w9b/1Of/5fj/AApNABtjACx5Aj2PE06gJF+xNXDCRoHTV5LkaKP1ebT/isX/m9b/rOf/vfj/zv//ABomACs8ADxSAE1oBl58F2+NKICeOZGvSqLAW7PRbMTifdXzjub/n/f/sP//wf//ACQLADUQAEYiAFc4BWhNFnleJ4pvOJuASayRWr2ia86zfN/EjfDVnv/lr//xwP/9ACcMADgRAEkWAFobEGsbIXwsMo09Q55OVK9fZcBwdtGBh+KSmPOjqf+zuv+/y//LACMKADQQBEUTFVYTJmcTN3gTSIkUWZolaqs2e7xHjM1Ynd5pru96v/+L0P+X4f+jABcHDigIHzkIMEoIQVsIUmwIY30IdI4NhZ8elrAvp8FAuNJRyeNi2vRz6/+C/P+O';

// Lospec mirror atari-2600-ntsc-wikipedia (127 of 128 entries cross-checked
// against MARIA_7800.lmc's shared hue ramps and TIA_2600.lmc; see the
// module comment for the one corrected transcription error).
export const TIA_2600_PAL_SOURCE: FixtureSource = {
  url: 'https://lospec.com/palette-list/atari-2600-ntsc-wikipedia',
  pathInArchive: 'Wikipedia "List of video game console palettes" 2600 NTSC table (128 colors, duplicated)',
};
export const TIA_2600_PAL_B64 =
  'AAAAAAAAQEBAQEBAbGxsbGxskJCQkJCQsLCwsLCwyMjIyMjI3Nzc3Nzc7Ozs7OzsREQAREQAZGQQZGQQhIQkhIQkoKA0oKA0uLhAuLhA0NBQ0NBQ6Ohc6Ohc/Pxo/PxocCgAcCgAhEQUhEQUmFwomFworHg8rHg8vIxMvIxMzKBczKBc3LRo3LRo7Mh47Mh4hBgAhBgAmDQYmDQYrFAwrFAwwGhIwGhI0IBc0IBc4JRw4JRw7KiA7KiA/LyU/LyUiAAAiAAAnCAgnCAgsDw8sDw8wFhYwFhY0HBw0HBw4IiI4IiI7KCg7KCg/LS0/LS0eABceABcjCB0jCB0oDyIoDyIsFicsFicwHCwwHCw0ITA0ITA3JzQ3JzQ7LDg7LDgSAB4SAB4YCCQYCCQeDykeDykjFi4jFi4oHDMoHDMtITctITcxJzsxJzs1LD81LD8FACEFACEMCCYMCCYTDysTDysaFjAaFjAfHDQfHDQlIjglIjgqKDsqKDsvLT8vLT8AACIAACIHCCcHCCcOECwOECwUFzAUFzAaHTQaHTQfIzgfIzgkKTskKTspLj8pLj8ABh8ABh8HDiQHDiQOFSoOFSoUHC8UHC8aIjMaIjMfJzcfJzckLTskLTspMj8pMj8ACxcACxcHEx4HEx4OGiQOGiQUISsUISsaJzAaJzAfLTUfLTUkMzokMzopOD8pOD8ADwsADwsHFxIHFxIOHxkOHxkUJyAUJyAaLSUaLSUfNCsfNCskOTAkOTApPzUpPzUADwAADwAIFwgIFwgQHxAQHxAXJxcXJxcdLR0dLR0jNCMjNCMpOSkpOSkuPy4uPy4FDgAFDgANFwcNFwcUHw4UHw4bJhQbJhQhLRohLRonMx8nMx8tOSQtOSQyPykyPykLDAALDAATFAcTFAcaHA0aHA0hIxMhIxMnKhknKhktMB4tMB4zNSIzNSI4Oyc4OycRCgARCgAZEgYZEgYhGgwhGgwoIREoIREuJxYuJxY0LRs0LRs6Mx86Mx8/OCM/OCM';

// MiSTer-devel/Atari7800_MiSTer commit 3dc43ee77c3ff538fc34a61293caaa7cbf5b642a,
// Palette/Trebors/NTSC/CALIBRATED/NTSC_CALIBRATED_COOL.pal. Breadth fixture
// only -- no official .lmc exists for any Trebor palette, so this asserts
// parse+convert success, never byte-identity.
export const TREBOR_COOL_PAL_SOURCE: FixtureSource = {
  url: 'https://raw.githubusercontent.com/MiSTer-devel/Atari7800_MiSTer/3dc43ee77c3ff538fc34a61293caaa7cbf5b642a/Palette/Trebors/NTSC/CALIBRATED/NTSC_CALIBRATED_COOL.pal',
  pathInArchive: 'Palette/Trebors/NTSC/CALIBRATED/NTSC_CALIBRATED_COOL.pal',
};
export const TREBOR_COOL_PAL_B64 =
  'AAAAERERIiIiMzMzREREVVVVZmZmd3d3iIiImZmZqqqqu7u7zMzM3d3d7u7u////FgoAJxsAOCwAST0AWk4Aa18AfHAAjYEFnpIWr6MnwLQ40cVJ4tZa8+dr//h8//+NLgAAPwkAUBoAYSsAcjwAg00AlF4ApW8QtoAhx5Ey2KJD6bNU+sRl/9V2/+aH//eYPQAATgAAXwoAcBsAgSwAkj0Oo04ftF8wxXBB1oFS55Jj+KN0/7SF/8WW/9an/+e4PwAAUAAAYQAIchAZgyEqlDI7pUNMtlRdx2Vu2HZ/6YeQ+pih/6my/7rD/8vU/9zlNgAZRwAqWAA7aQxMeh1diy5unD9/rVCQvmGhz3Ky4IPD8ZTU/6Xl/7b2/8f//9j/IgBHMwBYRABpVQ96ZiCLdzGciEKtmVO+qmTPu3XgzIbx3Zf/7qj//7n//8r//9v/BwBmGAB3KQmIOhqZSyuqXDy7bU3Mfl7dj2/uoID/sZH/wqL/07P/5MT/9dX//+b/AAByAAeDDBiUHSmlLjq2P0vHUFzYYW3pcn76g4//lKD/pbH/tsL/x9P/2OT/6fX/AAhnABl4ACqJBjuaF0yrKF28OW7NSn/eW5DvbKH/fbL/jsP/n9T/sOX/wfb/0v//ABhIAClZADpqAEt7CFyMGW2dKn6uO4+/TKDQXbHhbsLyf9P/kOT/ofX/sv//w///ACMaADQrAEU8AFZNBGdeFXhvJomAN5qRSKuiWbyzas3Ee97VjO/mnf/3rv//v///ACcAADgAAEkKAFobDmssH3w9MI1OQZ5fUq9wY8CBdNGSheKjlvO0p//FuP/Wyf/nACQAADUAAEYAEVcAImgAM3kPRIogVZsxZqxCd71TiM5kmd91qvCGu/+XzP+o3f+5ABoACisAGzwALE0APV4ATm8AX4AAcJERgaIikrMzo8REtNVVxeZm1vd35/+I+P+ZFQoAJhsANywASD0AWU4Aal8Ae3AAjIEFnZIWrqMnv7Q40MVJ4dZa8udr//h8//+N';

// Source: lumacode/MARIA_7800.lmc
export const MARIA_7800_LMC_SOURCE = firmwareLmc('lumacode/MARIA_7800.lmc');
export const MARIA_7800_LMC = `# RetroTINK LumaCode preset: Atari 7800
# First line = ADC sample rate and decimation, applied when loaded.
# Only NES timing is fully verified so far -- treat the sample rate and
# decimation here as a starting point and adjust in the menu if needed.
# The 7800 uses very narrow sync pulses -- sync settings may need tweaks.

3900 3

000000,111111,222222,333333,444444,555555,666666,777777,888888,999999,aaaaaa,bbbbbb,cccccc,dddddd,eeeeee,ffffff
001707,0e2808,1f3908,304a08,415b08,526c08,637d08,748e0d,859f1e,96b02f,a7c140,b8d251,c9e362,daf473,ebff82,fcff8e
1a0700,2b1800,3c2900,4d3a00,5e4b00,6f5c00,806d00,917e09,a28f1a,b3a02b,c4b13c,d5c24d,e6d35e,f7e46f,fff583,fff797
310000,420600,531700,642800,753900,864a00,975b0a,a86c1b,b97d2c,ca8e3d,db9f4e,ecb05f,fdc170,ffd285,ffe39c,fff4b2
3e0000,4f0000,600800,711900,822a0d,933b1e,a44c2f,b55d40,c66e51,d77f62,e89073,f9a183,ffb298,ffc3ae,ffd4c4,ffe5da
3f0003,50000f,61001b,720f2b,83203c,94314d,a5425e,b6536f,c76480,d87591,e986a2,fa97b3,ffa8c8,ffb9de,ffcaef,ffdbf4
330035,440041,55004c,660c5c,771d6d,882e7e,993f8f,aa50a0,bb61b1,cc72c2,dd83d3,ee94e4,ffa5e4,ffb6e9,ffc7ee,ffd8f3
1d005c,2e0068,400074,511084,622195,7332a6,8443b7,9554c8,a665d9,b776ea,c887eb,d998eb,e9a9ec,fbbaeb,ffcbef,ffdcf4
020071,13007d,240b8c,351c9d,462dae,573ebf,684fd0,7960e1,8a71f2,9b82f7,ac93f7,bda4f7,ceb5f7,dfc6f7,f0d7f7,ffe8f8
000068,000a7c,081b90,192ca1,2a3db2,3b4ec3,4c5fd4,5d70e5,6e81f6,7f92ff,90a3ff,a1b4ff,b2c5ff,c3d6ff,d4e7ff,e5f8ff
000a4d,001b63,002c79,023d8f,134ea0,245fb1,3570c2,4681d3,5792e4,68a3f5,79b4ff,8ac5ff,9bd6ff,ace7ff,bdf8ff,ceffff
001a26,002b3c,003c52,004d68,065e7c,176f8d,28809e,3991af,4aa2c0,5bb3d1,6cc4e2,7dd5f3,8ee6ff,9ff7ff,b0ffff,c1ffff
00240b,003510,004622,005738,05684d,16795e,278a6f,389b80,49ac91,5abda2,6bceb3,7cdfc4,8df0d5,9effe5,affff1,c0fffd
00270c,003811,004916,005a1b,106b1b,217c2c,328d3d,439e4e,54af5f,65c070,76d181,87e292,98f3a3,a9ffb3,baffbf,cbffcb
00230a,003410,044513,155613,266713,377813,488914,599a25,6aab36,7bbc47,8ccd58,9dde69,aeef7a,bfff8b,d0ff97,e1ffa3
001707,0e2808,1f3908,304a08,415b08,526c08,637d08,748e0d,859f1e,96b02f,a7c140,b8d251,c9e362,daf473,ebff82,fcff8e
`;

// Source: lumacode/TIA_2600.lmc
export const TIA_2600_LMC_SOURCE = firmwareLmc('lumacode/TIA_2600.lmc');
export const TIA_2600_LMC = `# RetroTINK LumaCode preset: Atari 2600
# First line = ADC sample rate and decimation, applied when loaded.
# Only NES timing is fully verified so far -- treat the sample rate and
# decimation here as a starting point and adjust in the menu if needed.
# Each color appears twice (the index's lowest bit is unused).

3648 4

000000,000000,404040,404040,6C6C6C,6C6C6C,909090,909090,B0B0B0,B0B0B0,C8C8C8,C8C8C8,DCDCDC,DCDCDC,ECECEC,ECECEC
444400,444400,646410,646410,848424,848424,A0A034,A0A034,B8B840,B8B840,D0D050,D0D050,E8E85C,E8E85C,FCFC68,FCFC68
702800,702800,844414,844414,985C28,985C28,AC783C,AC783C,BC8C4C,BC8C4C,CCA05C,CCA05C,DCB468,DCB468,ECC878,ECC878
841800,841800,983418,983418,AC5030,AC5030,C06848,C06848,D0805C,D0805C,E09470,E09470,ECA880,ECA880,FCBC94,FCBC94
880000,880000,9C2020,9C2020,B03C3C,B03C3C,C05858,C05858,D07070,D07070,E08888,E08888,ECA0A0,ECA0A0,FCB4B4,FCB4B4
78005C,78005C,8C2074,8C2074,A03C88,A03C88,B0589C,B0589C,C070B0,C070B0,D084C0,D084C0,DC9CD0,DC9CD0,ECB0E0,ECB0E0
480078,480078,602090,602090,783CA4,783CA4,8C58B8,8C58B8,A070CC,A070CC,B484DC,B484DC,C49CEC,C49CEC,D4B0FC,D4B0FC
140084,140084,302098,302098,4C3CAC,4C3CAC,6858C0,6858C0,7C70D0,7C70D0,9488E0,9488E0,A8A0EC,A8A0EC,BCB4FC,BCB4FC
000088,000088,1C209C,1C209C,3840B0,3840B0,505CC0,505CC0,6874D0,6874D0,7C8CE0,7C8CE0,90A4EC,90A4EC,A4B8FC,A4B8FC
00187C,00187C,1C3890,1C3890,3854A8,3854A8,5070BC,5070BC,6888CC,6888CC,7C9CDC,7C9CDC,90B4EC,90B4EC,A4C8FC,A4C8FC
002C5C,002C5C,1C4C78,1C4C78,386890,386890,5084AC,5084AC,689CC0,689CC0,7CB4D4,7CB4D4,90CCE8,90CCE8,A4E0FC,A4E0FC
003C2C,003C2C,1C5C48,1C5C48,387C64,387C64,509C80,509C80,68B494,68B494,7CD0AC,7CD0AC,90E4C0,90E4C0,A4FCD4,A4FCD4
003C00,003C00,205C20,205C20,407C40,407C40,5C9C5C,5C9C5C,74B474,74B474,8CD08C,8CD08C,A4E4A4,A4E4A4,B8FCB8,B8FCB8
143800,143800,345C1C,345C1C,507C38,507C38,6C9850,6C9850,84B468,84B468,9CCC7C,9CCC7C,B4E490,B4E490,C8FCA4,C8FCA4
2C3000,2C3000,4C501C,4C501C,687034,687034,848C4C,848C4C,9CA864,9CA864,B4C078,B4C078,CCD488,CCD488,E0EC9C,E0EC9C
442800,442800,644818,644818,846830,846830,A08444,A08444,B89C58,B89C58,D0B46C,D0B46C,E8CC7C,E8CC7C,FCE08C,FCE08C
`;

export interface GoldenPairTier2 {
  name: string;
  palBase64: string;
  palSource: FixtureSource;
  system: SystemId;
  lmcText: string;
  lmcSource: FixtureSource;
  expectedHeader: { rate: number; dec: number };
  isOracle: boolean;
}

export const GOLDEN_PAIRS_TIER2: GoldenPairTier2[] = [
  {
    name: 'MAME a7800p_colors -> MARIA_7800.lmc',
    palBase64: MARIA_7800_PAL_B64,
    palSource: MARIA_7800_PAL_SOURCE,
    system: 'a7800',
    lmcText: MARIA_7800_LMC,
    lmcSource: MARIA_7800_LMC_SOURCE,
    expectedHeader: { rate: 3900, dec: 3 },
    isOracle: true,
  },
  {
    name: 'Wikipedia 2600 NTSC table (duplicated) -> TIA_2600.lmc',
    palBase64: TIA_2600_PAL_B64,
    palSource: TIA_2600_PAL_SOURCE,
    system: 'a2600',
    lmcText: TIA_2600_LMC,
    lmcSource: TIA_2600_LMC_SOURCE,
    expectedHeader: { rate: 3648, dec: 4 },
    isOracle: true,
  },
];
